steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/chatbot-image', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/chatbot-image' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', 'chatbot',
            '--image', 'gcr.io/$PROJECT_ID/chatbot-image',
            '--platform', 'managed',
            '--region', 'us-central1',
            '--allow-unauthenticated' ]
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/chatbot-image', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/chatbot-image' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'run', 'deploy', 'chatbot',
            '--image', 'gcr.io/$PROJECT_ID/chatbot-image',
            '--platform', 'managed',
            '--region', 'us-central1',
            '--allow-unauthenticated' ]
